# Question 1
Given a 32x32 pixels, 3 channels input. Fill the pixel values
with torch.randn( . . . )

Foreach pytorch functions in the list,

1. Initialise the weights with uniform random numbers r
2. Call the functions and get the output tensors - torch_out
3. Implement these functions from scratch, without using
any neural network libraries. Use linear algebra libraries
in python is ok. Output your tensors as — my_out
4. Compare and show that torch_out and my_out are equal
up to small numerical errors

In [ ]:
import math
import random
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torchvision
input = torch.randn(1, 3, 32, 32)
target = torch.randn(1, 3, 32, 32)
input, input.shape

(tensor([[[[ 0.4838, -0.3118, -1.2532,  ...,  0.7453,  0.3793,  0.7554],
           [-0.2590,  0.4500, -0.1944,  ..., -1.0207, -1.1908,  0.8903],
           [ 1.1126,  0.3087,  0.9867,  ..., -0.0082, -2.0853, -1.0565],
           ...,
           [-1.9882,  0.2294, -1.5093,  ...,  1.4178,  0.1160,  0.6332],
           [-0.0938,  0.6729,  0.4040,  ...,  0.9509, -0.5742, -0.5498],
           [-0.2523, -1.4786, -1.3157,  ..., -0.3812,  1.2052,  0.2447]],
 
          [[ 1.4571,  0.4707,  0.4188,  ...,  0.2626,  1.2343, -0.3214],
           [ 1.3445, -0.7803,  0.7791,  ...,  1.4107,  0.5972,  1.3314],
           [ 0.6287, -0.0563,  0.2021,  ..., -0.1295,  1.5399, -0.7483],
           ...,
           [ 0.2280,  0.0551,  0.4643,  ..., -0.2403, -0.8288,  0.7202],
           [ 0.6798, -0.9179,  1.7759,  ..., -1.3718,  1.7411,  0.0222],
           [ 0.1445,  0.1931,  0.4914,  ..., -0.5598,  1.1573, -0.1604]],
 
          [[ 0.8385,  0.4070, -0.9919,  ...,  0.6325, -0.0812, -0.1393],
           [ 

----
1. torch.nn.MaxPool2d(kernel_size=2, stride=1, padding=0, dilation=1, return_indices=False, ceil_mode=False)
2. torch.nn.AvgPool2d(kernel_size=2, stride=1, padding=0, ceil_mode=False， count_include_pad=True, divisor_override=None)
3. torch.nn.Conv2d(in_channels=3, out_channels=6, kernel_size=3, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode=‘zeros')
4. torch.nn.Conv2d(in_channels=3, out_channels=6, kernel_size=5, stride=2， padding=0, dilation=2, groups=1, bias=True, padding_mode=‘zeros')
5. torch.nn.ConvTranspose2d(in_channels=3, out_channels=4, kernel_size=3, stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1, padding_mode='zeros')
1. torch.flatten(input, start_dim=0, end_dim=-1)
2. torch.sigmoid(input, *, out=None)
3. torchvision.ops.roi_pool(input: torch.Tensor, boxes: torch.Tensor， output_size: None, spatial_scale: float = 1.0)
4. torch.nn.functional.batch_norm(input, running_mean, running_var, weight=None, bias=None, training=False, momentum=0.1, eps=1e-05)
5. torch.nn.functional.cross_entropy(input, target, weight=None， size_average=None, ignore_index=-100, reduce=None, reduction=‘mean')
6. torch.nn.functional.mse_loss(input, target, size_average=None, reduce=None, reduction='mean')
----

## Max pooling

In [ ]:
mp = torch.nn.MaxPool2d(kernel_size=2, stride=1, padding=0, dilation=1, return_indices=False, ceil_mode=False)
torch_out = mp(input)[0]
torch_out, torch_out.shape

(tensor([[[ 0.4838,  0.4500,  2.5512,  ...,  0.7453,  0.7453,  0.8903],
          [ 1.1126,  0.9867,  0.9867,  ...,  0.6039, -0.0082,  0.8903],
          [ 1.9328,  1.9328,  0.9867,  ...,  2.1196, -0.0082,  0.4107],
          ...,
          [ 0.9626,  0.2294,  2.1630,  ...,  1.4178,  1.4178,  0.6332],
          [ 0.6729,  0.6729,  0.4040,  ...,  1.4178,  1.4178,  0.6332],
          [ 0.6729,  0.6729,  0.4040,  ...,  0.9509,  1.2052,  1.2052]],
 
         [[ 1.4571,  0.7791,  1.5508,  ...,  1.4107,  1.4107,  1.3314],
          [ 1.3445,  0.7791,  1.5508,  ...,  1.4107,  1.5399,  1.5399],
          [ 2.8187,  1.3214,  2.2493,  ...,  1.0530,  1.5399,  1.5399],
          ...,
          [ 0.7987,  1.0814,  1.5740,  ...,  0.8206,  0.8206,  1.1339],
          [ 0.6798,  1.7759,  1.7759,  ...,  0.4105,  1.7411,  1.7411],
          [ 0.6798,  1.7759,  1.7759,  ...,  0.4414,  1.7411,  1.7411]],
 
         [[ 0.8385,  0.8495,  1.2247,  ...,  0.6325,  1.3094,  1.3094],
          [ 0.6785,  0.8495,

In [ ]:
def maxpool2d(input, kernal_size, stride):
    minibatch = input.shape[0]
    channel_size = input.shape[1]
    img_size = input.shape[2]
    output = torch.zeros(minibatch, channel_size, int((img_size - kernal_size) / stride) + 1, int((img_size - kernal_size) / stride) + 1)
    for pic_i in range(minibatch):
        for channel_i in range(channel_size):
            for img_i in range(output.shape[2]):
                for img_j in range(output.shape[2]):
                    list = []
                    for kernal_i in range(kernal_size):         
                        for kernal_j in range(kernal_size): 
                            list.append(input[pic_i][channel_i][img_i*stride+kernal_i][img_j*stride+kernal_j])
                    output[pic_i][channel_i][img_i][img_j] = max(list)
    return output

my_out = maxpool2d(input, kernal_size=2, stride=1)[0]

In [ ]:
torch.sum(my_out - torch_out) < 1e-6

tensor(True)

## Average pooling

In [ ]:
ap = torch.nn.AvgPool2d(kernel_size=2, stride=1, padding=0, ceil_mode=False, count_include_pad=True, divisor_override=None)
torch_out = ap(input)[0]
torch_out, torch_out.shape

(tensor([[[ 9.0767e-02, -3.2734e-01,  6.7748e-02,  ...,  1.4631e-01,
           -2.7173e-01,  2.0857e-01],
          [ 4.0308e-01,  3.8777e-01,  3.1742e-02,  ..., -1.8086e-01,
           -1.0763e+00, -8.6055e-01],
          [ 4.3177e-01,  1.0474e+00,  6.7569e-01,  ...,  2.6735e-01,
           -7.3889e-01, -7.1239e-01],
          ...,
          [-2.9278e-01, -4.8024e-01, -1.3697e-04,  ...,  4.5748e-01,
            6.4603e-02,  1.7363e-01],
          [-2.9492e-01, -5.0740e-02, -7.7347e-01,  ...,  9.4661e-01,
            4.7763e-01, -9.3696e-02],
          [-2.8795e-01, -4.2936e-01, -6.4597e-01,  ...,  3.6319e-01,
            3.0017e-01,  8.1472e-02]],
 
         [[ 6.2298e-01,  2.2207e-01,  6.3295e-01,  ...,  5.8086e-01,
            8.7620e-01,  7.1039e-01],
          [ 2.8413e-01,  3.6131e-02,  4.5692e-01,  ...,  4.9120e-01,
            8.5458e-01,  6.8006e-01],
          [ 1.1781e+00,  2.2222e-01,  2.9220e-01,  ...,  5.2331e-01,
            2.7202e-01,  8.6156e-02],
          ...,
    

In [ ]:
def avgpool2d(input, kernal_size, stride):
    minibatch = input.shape[0]
    channel_size = input.shape[1]
    img_size = input.shape[2]
    output = torch.zeros(minibatch, channel_size, int((img_size - kernal_size) / stride) + 1, int((img_size - kernal_size) / stride) + 1)
    for pic_i in range(minibatch):
        for channel_i in range(channel_size):
            for img_i in range(output.shape[2]):
                for img_j in range(output.shape[2]):
                    list = []
                    for kernal_i in range(kernal_size):         
                        for kernal_j in range(kernal_size): 
                            list.append(input[pic_i][channel_i][img_i*stride+kernal_i][img_j*stride+kernal_j])
                    output[pic_i][channel_i][img_i][img_j] = sum(list)/len(list)
    return output

my_out = avgpool2d(input, kernal_size=2, stride=1)

In [ ]:
torch.sum(my_out - torch_out) < 1e-6

tensor(True)

## Conv2D (dilation = 1)

In [ ]:
torch_conv2d = torch.nn.Conv2d(in_channels=3, out_channels=6, kernel_size=3, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros')
torch_out = torch_conv2d(input)[0]
torch_out, torch_out.shape

(tensor([[[ 0.0336, -0.2698, -0.5240,  ..., -0.2100, -0.7646, -0.7319],
          [ 1.0819, -0.3942,  0.0715,  ..., -0.9504, -0.5865, -0.6294],
          [ 0.3854,  0.3837, -0.3733,  ...,  1.0239, -1.3277,  0.6839],
          ...,
          [-1.0192,  1.5937,  0.0737,  ..., -0.0395, -1.4077, -0.2966],
          [-0.1376, -1.2068, -0.0756,  ...,  1.2121, -0.0460, -0.3485],
          [-1.3781, -0.4653, -0.7192,  ...,  0.0174,  0.1745, -0.0348]],
 
         [[-0.4848,  0.6013,  0.3544,  ...,  0.2888, -0.5132,  0.5391],
          [-0.2680,  0.7958,  0.1893,  ...,  1.1370, -0.7283,  0.1398],
          [-0.1752,  0.0985,  0.6900,  ...,  0.5283, -0.4834,  0.3106],
          ...,
          [-1.0220,  0.3741,  0.3945,  ...,  0.0234,  0.4341, -0.2120],
          [ 0.2361,  1.5782, -0.8830,  ..., -0.2017, -0.5385,  0.3292],
          [-0.3811,  1.4689, -1.9326,  ..., -0.1188,  0.2955,  1.5410]],
 
         [[ 0.2729,  0.1140, -0.0986,  ...,  0.2860, -0.4853, -0.4808],
          [ 0.8209,  0.0293,

In [ ]:
def conv2d(input, out_channels, kernel_size, stride, dilation, weight_from_torch, bias_from_torch):
    minibatch = input.shape[0]
    channel_size = input.shape[1]
    img_size = input.shape[2]
    dilation_kernel_size = kernel_size + (kernel_size-1)*(dilation-1)
    output = torch.zeros(minibatch, out_channels, int((img_size - dilation_kernel_size) / stride) + 1, 
                         int((img_size - dilation_kernel_size) / stride) + 1)
    for pic_i in range(minibatch):
        for out_channel_i in range(out_channels):
            for channel_i in range(channel_size):
                for img_i in range(output.shape[2]):
                    for img_j in range(output.shape[2]):
                        sum_list = []
                        for kernal_i in range(kernel_size):         
                            for kernal_j in range(kernel_size): 
                                sum_list.append((input[pic_i][channel_i][img_i*stride+kernal_i*dilation][img_j*stride+kernal_j*dilation])*
                                (weight_from_torch[out_channel_i][channel_i][kernal_i][kernal_j]))
                        output[pic_i][out_channel_i][img_i][img_j] = output[pic_i][out_channel_i][img_i][img_j] + sum(sum_list)
            output[pic_i][out_channel_i] = output[pic_i][out_channel_i]+bias_from_torch[out_channel_i]
    return output
my_out = conv2d(input, out_channels=6, kernel_size=3, stride=1, dilation=1, weight_from_torch = torch_conv2d.weight, bias_from_torch=torch_conv2d.bias)[0]
my_out, my_out.shape

(tensor([[[ 0.0336, -0.2698, -0.5240,  ..., -0.2100, -0.7646, -0.7319],
          [ 1.0819, -0.3942,  0.0715,  ..., -0.9504, -0.5865, -0.6294],
          [ 0.3854,  0.3837, -0.3733,  ...,  1.0239, -1.3277,  0.6839],
          ...,
          [-1.0192,  1.5937,  0.0737,  ..., -0.0395, -1.4077, -0.2966],
          [-0.1376, -1.2068, -0.0756,  ...,  1.2121, -0.0460, -0.3485],
          [-1.3781, -0.4653, -0.7192,  ...,  0.0174,  0.1745, -0.0348]],
 
         [[-0.4848,  0.6013,  0.3544,  ...,  0.2888, -0.5132,  0.5391],
          [-0.2680,  0.7958,  0.1893,  ...,  1.1370, -0.7283,  0.1398],
          [-0.1752,  0.0985,  0.6900,  ...,  0.5283, -0.4834,  0.3106],
          ...,
          [-1.0220,  0.3741,  0.3945,  ...,  0.0234,  0.4341, -0.2120],
          [ 0.2361,  1.5782, -0.8830,  ..., -0.2017, -0.5385,  0.3292],
          [-0.3811,  1.4689, -1.9326,  ..., -0.1188,  0.2955,  1.5410]],
 
         [[ 0.2729,  0.1140, -0.0986,  ...,  0.2860, -0.4853, -0.4808],
          [ 0.8209,  0.0293,

In [ ]:
torch.sum(my_out - torch_out) < 1e-6

tensor(False)

## Conv2D (dilation = 2)

In [ ]:
torch_conv2d = torch.nn.Conv2d(in_channels=3, out_channels=6, kernel_size=5, stride=2, padding=0, dilation=2, groups=1, bias=True, padding_mode='zeros')
torch_out = torch_conv2d(input)[0]
torch_out, torch_out.shape

(tensor([[[ 5.4906e-01, -9.9367e-01,  1.9784e-02,  7.0454e-02, -2.0152e-01,
            6.6573e-01,  5.5164e-02, -4.3342e-01, -2.5017e-01, -3.6095e-01,
           -1.4940e-01, -3.0109e-01],
          [ 4.3019e-01,  7.9175e-01, -2.7404e-01,  9.2779e-01, -8.6376e-01,
           -5.1132e-01,  1.0530e-01,  3.3608e-01, -4.4353e-01,  7.1229e-01,
            3.3270e-01, -6.4321e-01],
          [ 3.1465e-01, -4.7778e-01, -1.1592e-01, -1.1453e-01, -7.1018e-01,
            2.1801e-01, -2.9093e-01,  1.8154e-01,  6.2650e-01, -2.8813e-01,
            2.9067e-01,  2.8454e-01],
          [-3.7684e-01, -6.5582e-01, -3.7002e-01, -8.3488e-01,  1.1244e-01,
            6.1739e-02,  4.1493e-01, -3.4223e-02, -9.6219e-01, -7.9688e-01,
           -8.7136e-01,  6.9190e-01],
          [-1.1850e+00, -5.1333e-01,  4.2294e-01, -5.9603e-01, -8.1962e-01,
            4.3662e-01, -8.4864e-02, -4.2215e-01,  7.1957e-01, -3.0692e-01,
            1.9350e-01, -9.9890e-01],
          [-4.3161e-01,  2.8271e-02, -5.0274e-01, 

In [ ]:
my_out = conv2d(input, out_channels=6, kernel_size=5, stride=2, dilation=2, weight_from_torch = torch_conv2d.weight, bias_from_torch=torch_conv2d.bias)[0]
my_out, my_out.shape

(tensor([[[ 5.4906e-01, -9.9367e-01,  1.9784e-02,  7.0454e-02, -2.0152e-01,
            6.6573e-01,  5.5164e-02, -4.3342e-01, -2.5017e-01, -3.6095e-01,
           -1.4940e-01, -3.0109e-01],
          [ 4.3019e-01,  7.9175e-01, -2.7404e-01,  9.2779e-01, -8.6376e-01,
           -5.1132e-01,  1.0530e-01,  3.3608e-01, -4.4353e-01,  7.1229e-01,
            3.3270e-01, -6.4321e-01],
          [ 3.1465e-01, -4.7778e-01, -1.1592e-01, -1.1453e-01, -7.1018e-01,
            2.1801e-01, -2.9093e-01,  1.8154e-01,  6.2650e-01, -2.8813e-01,
            2.9067e-01,  2.8454e-01],
          [-3.7684e-01, -6.5582e-01, -3.7002e-01, -8.3488e-01,  1.1244e-01,
            6.1740e-02,  4.1493e-01, -3.4223e-02, -9.6219e-01, -7.9688e-01,
           -8.7136e-01,  6.9190e-01],
          [-1.1850e+00, -5.1333e-01,  4.2294e-01, -5.9603e-01, -8.1962e-01,
            4.3662e-01, -8.4864e-02, -4.2215e-01,  7.1957e-01, -3.0692e-01,
            1.9350e-01, -9.9890e-01],
          [-4.3161e-01,  2.8271e-02, -5.0274e-01, 

In [ ]:
torch.sum(my_out - torch_out) < 1e-6

tensor(False)

## ConvTranspose2d

In [ ]:
torch_ct = torch.nn.ConvTranspose2d(in_channels=3, out_channels=4, kernel_size=3, stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1, padding_mode='zeros')
torch_out = torch_ct(input)
torch_out

tensor([[[[ 4.1845e-02, -1.6714e-01, -1.8842e-01,  ...,  7.0044e-02,
            5.2133e-03,  1.7250e-01],
          [ 1.3501e-01, -9.7834e-02,  5.0259e-01,  ...,  3.6967e-02,
           -2.0127e-01,  1.6275e-01],
          [ 6.2553e-01,  4.8631e-02,  3.7367e-01,  ...,  6.7989e-01,
            1.8079e-01,  2.9000e-01],
          ...,
          [-9.4956e-02, -2.3312e-01,  3.3862e-01,  ...,  2.6984e-01,
            4.2579e-01,  1.2483e-01],
          [ 1.4532e-01,  3.3738e-01,  3.6366e-01,  ..., -4.9004e-01,
            3.1808e-01,  9.5034e-02],
          [ 3.2635e-02, -2.7606e-03, -1.1109e-01,  ...,  2.3485e-01,
            2.2020e-01,  1.3011e-01]],

         [[ 5.6228e-02,  1.1906e-01,  1.8120e-01,  ...,  1.2681e-02,
           -2.9627e-01,  1.0890e-01],
          [ 4.1768e-02, -1.6511e-01, -2.0744e-01,  ..., -5.9173e-02,
           -2.2010e-02,  1.8467e-02],
          [-2.8598e-01, -4.3770e-01,  5.0407e-02,  ...,  2.2101e-01,
           -2.4243e-01,  1.0327e-01],
          ...,
     

In [ ]:
def convT(x, in_channels, out_channels, kernel_size, stride, weight, bias, dilation):

    x_batch = x.size(0)
    x_channel = x.size(1)
    x_height = x.size(2)
    x_width = x.size(3)
    
    kernel_height = kernel_size[0]
    kernel_width = kernel_size[1]

    y_height = (x_height + kernel_height) - 1
    y_width = (x_width + kernel_width) - 1
    y_channels = out_channels
    y = torch.zeros((x_batch, y_channels, y_height, y_width))
    
    for a in range(x_batch):
      for b in range(y_channels):
        for c in range(x_channel):
          for i in range(x_height):
            for j in range(x_width):
              y[a, b, i:i + kernel_height, j:j + kernel_width] += x[a, c, i, j] * weight[c][b]
    
    for i in range(y_channels):
      y[0][i] += bias[i]

    return y

my_out = convT(input, in_channels = 3, out_channels = 4, kernel_size = (3, 3), stride = 1, weight = torch_ct.weight, bias = torch_ct.bias, dilation = 1)
my_out

tensor([[[[ 4.1845e-02, -1.6714e-01, -1.8842e-01,  ...,  7.0044e-02,
            5.2133e-03,  1.7250e-01],
          [ 1.3501e-01, -9.7834e-02,  5.0259e-01,  ...,  3.6967e-02,
           -2.0127e-01,  1.6275e-01],
          [ 6.2553e-01,  4.8631e-02,  3.7367e-01,  ...,  6.7989e-01,
            1.8079e-01,  2.9000e-01],
          ...,
          [-9.4956e-02, -2.3312e-01,  3.3862e-01,  ...,  2.6984e-01,
            4.2579e-01,  1.2483e-01],
          [ 1.4532e-01,  3.3738e-01,  3.6366e-01,  ..., -4.9004e-01,
            3.1808e-01,  9.5034e-02],
          [ 3.2635e-02, -2.7606e-03, -1.1109e-01,  ...,  2.3485e-01,
            2.2020e-01,  1.3011e-01]],

         [[ 5.6228e-02,  1.1906e-01,  1.8120e-01,  ...,  1.2681e-02,
           -2.9627e-01,  1.0890e-01],
          [ 4.1768e-02, -1.6511e-01, -2.0744e-01,  ..., -5.9173e-02,
           -2.2010e-02,  1.8467e-02],
          [-2.8598e-01, -4.3770e-01,  5.0407e-02,  ...,  2.2101e-01,
           -2.4243e-01,  1.0327e-01],
          ...,
     

In [ ]:
torch.sum(my_out - torch_out) < 1e-6

tensor(True)

## flatten

In [ ]:
input = torch.randn(1, 3, 32, 32)
torch_out = torch.flatten(input, start_dim=0, end_dim=-1)
torch_out, torch_out.shape

(tensor([ 0.3671, -0.9594, -1.9024,  ...,  0.1655,  0.7854, -2.1835]),
 torch.Size([3072]))

In [ ]:
my_out = torch.stack([d for a in input for b in a for c in b for d in c])
my_out, my_out.shape

(tensor([ 0.3671, -0.9594, -1.9024,  ...,  0.1655,  0.7854, -2.1835]),
 torch.Size([3072]))

In [ ]:
torch.sum(my_out - torch_out) < 1e-6

tensor(True)

## sigmoid

In [ ]:
# Given a 32x32 pixels, 3 channels input. Fill the pixel values with torch.randn( . . . )
input = torch.randn(1, 3, 32, 32)
torch_out = torch.sigmoid(input, out=None)
torch_out

tensor([[[[0.1615, 0.7463, 0.5190,  ..., 0.3358, 0.3952, 0.3605],
          [0.7709, 0.7897, 0.7258,  ..., 0.8253, 0.7736, 0.6955],
          [0.1973, 0.1655, 0.9003,  ..., 0.1020, 0.1828, 0.6286],
          ...,
          [0.3811, 0.4927, 0.1006,  ..., 0.1545, 0.3114, 0.9344],
          [0.3140, 0.2559, 0.6360,  ..., 0.5818, 0.6252, 0.6322],
          [0.6173, 0.8123, 0.5094,  ..., 0.3189, 0.5511, 0.3431]],

         [[0.7114, 0.7385, 0.5067,  ..., 0.2983, 0.7252, 0.5145],
          [0.6745, 0.7719, 0.3058,  ..., 0.6627, 0.6236, 0.7635],
          [0.8032, 0.7624, 0.5510,  ..., 0.4863, 0.4519, 0.8443],
          ...,
          [0.5350, 0.6514, 0.4990,  ..., 0.2776, 0.2535, 0.3405],
          [0.6047, 0.3355, 0.8097,  ..., 0.3089, 0.2332, 0.2206],
          [0.3108, 0.0628, 0.2396,  ..., 0.5816, 0.2521, 0.2204]],

         [[0.4947, 0.1488, 0.2982,  ..., 0.7342, 0.7641, 0.3409],
          [0.6828, 0.3527, 0.7789,  ..., 0.5939, 0.2717, 0.7348],
          [0.4770, 0.2492, 0.2871,  ..., 0

In [ ]:
my_out = 1 / (1 + np.exp(-input))
my_out

tensor([[[[0.1615, 0.7463, 0.5190,  ..., 0.3358, 0.3952, 0.3605],
          [0.7709, 0.7897, 0.7258,  ..., 0.8253, 0.7736, 0.6955],
          [0.1973, 0.1655, 0.9003,  ..., 0.1020, 0.1828, 0.6286],
          ...,
          [0.3811, 0.4927, 0.1006,  ..., 0.1545, 0.3114, 0.9344],
          [0.3140, 0.2559, 0.6360,  ..., 0.5818, 0.6252, 0.6322],
          [0.6173, 0.8123, 0.5094,  ..., 0.3189, 0.5511, 0.3431]],

         [[0.7114, 0.7385, 0.5067,  ..., 0.2983, 0.7252, 0.5145],
          [0.6745, 0.7719, 0.3058,  ..., 0.6627, 0.6236, 0.7635],
          [0.8032, 0.7624, 0.5510,  ..., 0.4863, 0.4519, 0.8443],
          ...,
          [0.5350, 0.6514, 0.4990,  ..., 0.2776, 0.2535, 0.3405],
          [0.6047, 0.3355, 0.8097,  ..., 0.3089, 0.2332, 0.2206],
          [0.3108, 0.0628, 0.2396,  ..., 0.5816, 0.2521, 0.2204]],

         [[0.4947, 0.1488, 0.2982,  ..., 0.7342, 0.7641, 0.3409],
          [0.6828, 0.3527, 0.7789,  ..., 0.5939, 0.2717, 0.7348],
          [0.4770, 0.2492, 0.2871,  ..., 0

In [ ]:
torch.sum(my_out - torch_out) < 1e-5

tensor(True)

## roi_pool

In [ ]:
# https://zhuanlan.zhihu.com/p/104361606
boxes = torch.Tensor([[0, 0, 0, 15, 15]])
torch_out = torchvision.ops.roi_pool(input, boxes, (4, 4))
torch_out

tensor([[[[2.2750, 0.9144, 1.2636, 2.6015],
          [1.2245, 1.5648, 2.8611, 2.7959],
          [0.9688, 0.8708, 1.5210, 1.1420],
          [1.2913, 1.5374, 1.3457, 1.8274]],

         [[1.0782, 0.9836, 1.4259, 1.9334],
          [2.0286, 2.0986, 1.7469, 1.0511],
          [2.7110, 1.5762, 3.8811, 1.6735],
          [1.7006, 1.5028, 2.6696, 1.2508]],

         [[2.0669, 1.3363, 2.6361, 1.8743],
          [2.2111, 3.4064, 1.1528, 1.0870],
          [1.8582, 1.0525, 2.5315, 1.7048],
          [1.4762, 2.0592, 2.3224, 0.6824]]]])

In [ ]:
def my_roi_pool(X, boxes, output_size):
    
    roi_start_height = int(boxes[0][1])
    roi_start_width = int(boxes[0][2])
    roi_end_height = int(boxes[0][3])
    roi_end_width = int(boxes[0][4])
    
    roi_width = roi_end_width - roi_start_width + 1
    roi_height = roi_end_height - roi_start_height + 1

    bin_width = roi_width / output_size[0]
    bin_height = roi_height / output_size[1]
    
    result = []
    for i in range(X.shape[1]):
      tmp = []
      for j in range(output_size[0]):
        r = []
        for k in range(output_size[1]):
          temp = X[..., int(roi_start_height + bin_height * j):math.ceil(roi_start_height + bin_height * (j + 1)), 
                   int(roi_start_width + bin_width * k):math.ceil(roi_start_width + bin_width * (k + 1))][0][i]
          r.append(temp.max())
        tmp.append(r)
      result.append(tmp)

    result = torch.Tensor(result)
    result = result.unsqueeze(0)
    return result
  
my_out = my_roi_pool(input, boxes, (4, 4))
my_out

tensor([[[[2.2750, 0.9144, 1.2636, 2.6015],
          [1.2245, 1.5648, 2.8611, 2.7959],
          [0.9688, 0.8708, 1.5210, 1.1420],
          [1.2913, 1.5374, 1.3457, 1.8274]],

         [[1.0782, 0.9836, 1.4259, 1.9334],
          [2.0286, 2.0986, 1.7469, 1.0511],
          [2.7110, 1.5762, 3.8811, 1.6735],
          [1.7006, 1.5028, 2.6696, 1.2508]],

         [[2.0669, 1.3363, 2.6361, 1.8743],
          [2.2111, 3.4064, 1.1528, 1.0870],
          [1.8582, 1.0525, 2.5315, 1.7048],
          [1.4762, 2.0592, 2.3224, 0.6824]]]])

In [ ]:
torch.sum(my_out - torch_out) < 1e-6

tensor(True)

## batch_norm

In [ ]:
# inp is shape (N, C, H, W)
input = torch.randn(1, 3, 32, 32)
n_chans = input.shape[1]
running_mean = torch.Tensor([input[0][i].mean() for i in range(input.shape[1])])
running_var = torch.Tensor([input[0][i].var() for i in range(input.shape[1])])
torch_out = torch.nn.functional.batch_norm(input, running_mean, running_var, weight=None, bias=None, training=False, momentum=0.1, eps=1e-05)
torch_out

tensor([[[[-0.9180,  0.4204,  1.2681,  ...,  1.0045,  0.1069,  0.1421],
          [ 1.2863,  0.7909,  0.0246,  ...,  0.0820,  1.1645, -1.1325],
          [ 1.1722, -1.1650, -0.0292,  ..., -0.3071,  2.6611,  1.1739],
          ...,
          [ 0.0335, -0.3208, -1.5693,  ..., -0.9619, -0.8820,  1.3211],
          [-1.9693,  0.1257, -1.0871,  ..., -1.9360,  1.1293,  0.7241],
          [-0.0455, -0.0698, -0.3569,  ..., -0.6001,  0.2748, -1.4142]],

         [[-0.8818,  1.6415,  0.4700,  ..., -0.5673,  1.8877, -0.2711],
          [ 1.0450, -2.3461, -2.1158,  ...,  0.6212, -1.2547,  0.4891],
          [ 0.3650, -1.5809,  1.1113,  ..., -1.8371, -0.4925, -0.8205],
          ...,
          [-0.6335,  1.1719, -1.5569,  ..., -0.4759, -1.8943,  0.4749],
          [ 0.8690, -0.5901,  0.6322,  ...,  0.5941, -0.9371, -0.4747],
          [ 0.6949,  0.1446, -0.6748,  ...,  0.2078, -1.7994,  0.3911]],

         [[ 0.6996,  1.1996,  1.9263,  ..., -0.3207, -1.1042, -0.5187],
          [-0.6849, -0.3876,  

In [ ]:
running_mean = torch.Tensor([input[0][i].mean() for i in range(input.shape[1])])
running_var = torch.Tensor([input[0][i].var() for i in range(input.shape[1])])

def batch_norm(input,mean,var, momentum, eps):
    output = torch.zeros(input.shape)
    for i in range(input.shape[1]):
        output[0][i] = (input[0][i] - mean[i])/(np.sqrt(var[i])-eps)
    return output
my_out = batch_norm(input, running_mean, running_var, momentum=0.1, eps=1e-05)
my_out

tensor([[[[-0.9180,  0.4204,  1.2681,  ...,  1.0046,  0.1069,  0.1421],
          [ 1.2863,  0.7909,  0.0246,  ...,  0.0820,  1.1645, -1.1325],
          [ 1.1722, -1.1650, -0.0292,  ..., -0.3071,  2.6611,  1.1740],
          ...,
          [ 0.0335, -0.3208, -1.5693,  ..., -0.9619, -0.8820,  1.3211],
          [-1.9693,  0.1257, -1.0871,  ..., -1.9360,  1.1293,  0.7241],
          [-0.0455, -0.0698, -0.3569,  ..., -0.6001,  0.2748, -1.4142]],

         [[-0.8818,  1.6415,  0.4700,  ..., -0.5673,  1.8877, -0.2711],
          [ 1.0450, -2.3461, -2.1158,  ...,  0.6212, -1.2547,  0.4891],
          [ 0.3650, -1.5809,  1.1113,  ..., -1.8371, -0.4925, -0.8205],
          ...,
          [-0.6335,  1.1720, -1.5569,  ..., -0.4760, -1.8943,  0.4749],
          [ 0.8691, -0.5901,  0.6323,  ...,  0.5941, -0.9371, -0.4747],
          [ 0.6949,  0.1446, -0.6748,  ...,  0.2078, -1.7994,  0.3911]],

         [[ 0.6996,  1.1997,  1.9264,  ..., -0.3207, -1.1042, -0.5187],
          [-0.6849, -0.3876,  

In [ ]:
torch.sum(my_out - torch_out) < 1e-4 # not as accurate...

tensor(True)

## cross_entropy

In [ ]:
input = torch.randn([1, 3, 32, 32])
target = torch.randint(3, (1, 32, 32), dtype=torch.int64)

In [ ]:
torch_out = torch.nn.functional.cross_entropy(input, target, weight=None, size_average=None, ignore_index=-100, reduce=None, reduction='mean')
torch_out

tensor(1.3893)

In [ ]:
def softmax(x):
    res = torch.zeros(x.shape)
    for i in range(len(x)):
        exp = torch.exp(x[i])
        sum = torch.sum(exp, dim=0)
        softmax = exp/sum
        res[i] = -torch.log(softmax)
    return res
    
def nn_loss(input, target):
    loss_list = torch.zeros([len(input)])
    for k in range(len(input)):
        loss = 0
        for i in range(target[k].shape[1]):
            for j in range(target.shape[2]):
                index = target[k, i, j]
                num = input[k, index, i ,j]
                loss -= num
        loss_list[k] = -loss / target.shape[1] / target.shape[2]
    return loss_list

def cross_entropy(input, target):
    log_softmax = softmax(input)
    loss = nn_loss(log_softmax, target)
    return loss.mean()

my_out = cross_entropy(input, target)
my_out

tensor(1.3893)

In [ ]:
torch.sum(my_out - torch_out) < .01

tensor(True)

## mse_loss

In [ ]:
input = torch.randn(1, 3, 32, 32)
target = torch.randn(1, 3, 32, 32)
torch_out = torch.nn.functional.mse_loss(input, target, size_average=None, reduce=None, reduction='mean')
torch_out

tensor(2.0407)

In [ ]:
my_out = ((input - target) ** 2).mean()
my_out

tensor(2.0407)

In [ ]:
torch.sum(my_out - torch_out) < 1e-6

tensor(True)